package com.example.poasystentrekrutacji.constant;

public enum Przedmiot {
    JEZYK_POLSKI,
    MATEMATYKA,
    HISTORIA,
    FIZYKA,
    JEZYK_ANGIELSKI,
    CHEMIA,
    BIOLOGIA,
    JEZYK_NIEMIECKI,
    JEZYK_ROSYJSKI,
    JEZYK_FRANCUSKI,
    JEZYK_HISZPANSKI,
    JEZYK_WLOSKI,
    FILOZOFIA,
    GEOGRAFIA,
    HISTORIA_MUZYKI,
    HISTORIA_SZTUKI,
    INFORMATYKA,
    WIEDZA_O_SPOLECZENSTWIE,
    JEZYK_BIALORUSKI,
    JEZYK_LITEWSKI,
    JEZYK_UKRAINSKI,
    JEZYK_KASZUBSKI
}
